name: adhyayan
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'




dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar: ^6.2.1
  calendar_slider: ^0.0.4
  intl: ^0.19.0
  get: ^4.6.6




dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0




flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sub/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
